name: stegan
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  image_picker: ^0.8.6
  path: ^1.8.0
  path_provider: ^2.0.0
  gallery_saver: 
  stegify:
    path: packages/stegify
  image_size_getter: ^2.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: 


flutter:

  
  uses-material-design: true
  assets:
    - assets/
  
  
  
  

